version: 2
jobs:
  build:
    docker:
      - image: python:3.5.5
    steps:
      - checkout
      - run:
          name: 'Setup virtualenv'
          command: |
            mkdir -p ~/.virtualenvs
            python3 -m venv ~/.virtualenvs/target-stitch
            source ~/.virtualenvs/target-stitch/bin/activate
            pip install -U pip setuptools
            pip install -e .[dev]
            pip install -U pylint
      - run:
          name: 'Run tests'
          command: |
            # Need to re-activate the virtualenv
            source ~/.virtualenvs/target-stitch/bin/activate
            nosetests -v tests/activate_version_tests.py
            nosetests -v --ignore-files=activate_version_tests.py
            #nosetests
            pylint target_stitch "--extension-pkg-whitelist=ciso8601"
